services: 
  db:
    image: "postgres:16.2-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres_data:
